doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/App'
        # List of additional migration classes to be loaded, optional
        #migrations:
        #    - 'src/App\Migrations\Version123'
        dir_name: '%kernel.project_dir%/src/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
        namespace: DoctrineMigrations
