version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'video_7.3x-webserver'
    restart: 'always'
    ports:
      - "${PROJECTPORTPREFIX}${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${PROJECTPORTPREFIX}${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ./www:/var/www/html
      - ./www/.env:/var/www/html/.env
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./data/composer_cache:/.composer/cache/files/
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'video_5.7-mysql'
    restart: 'always'
    ports:
      - "${PROJECTPORTPREFIX}${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'video_phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '8080:8080'
    volumes: 
      - /sessions
  redis:
    container_name: 'video_redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
    depends_on:
      - webserver
  redisadmin:
    image: 'rediscommander/redis-commander:latest'
    environment:
      - REDIS_HOST=video_redis
    ports:
      - '${PROJECTPORTPREFIX}083:8081'
