create table film
(
    id          int auto_increment
        primary key,
    owner_id    int          not null,
    title       varchar(255) not null,
    description varchar(512) not null,
    created_at  datetime     not null,
    constraint FK_8244BE227E3C61F9
        foreign key (owner_id) references user (id)
)
    collate = utf8mb4_unicode_ci;

create index IDX_8244BE227E3C61F9
    on film (owner_id);

INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (1, 'Coco', 'Despite his family''s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel''s family history.', '2020-09-26 11:32:44');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (2, 'Spider-Man: Into the Spider-Verse ', 'Miles Morales comes across the long-dead Peter Parker. This Peter Parker is not from his world though; he''s from somewhere else in the multiverse. With Parker''s guidance, Miles will become Spider-Man: and through that he will become part of the ever-expanding ''Spider-Verse''.', '2020-09-21 11:32:44');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (3, 'Princess Mononoke', 'A prince is infected with an incurable disease by a possessed boar/god. He is to die unless he can find a cure to rid the curse from his body. It seems that his only hope is to travel to the far east. When he arrives to get help from the deer god, he finds himself in the middle of a battle between the animal inhabitants of the forest and an iron mining town that is exploiting and killing the forest. Leading the forest animals in the battle is a human raised by wolves, Princess Mononoke.', '2020-09-21 11:32:44');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (4, 'Joker', 'Year 1981. In Gotham City, mentally-troubled Arthur Fleck (Joaquin Phoenix) works as a clown-for-hire and lives with his mother, Penny. Arthur, whose motivation in life is to make people laugh, wants to be a stand-up comedian, but he is ignored by society, and a series of tragic events will take him to see the world in a different way, full of anger and rage against everyone and everything.', '2020-09-27 09:41:24');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (5, 'Interestellar', 'In the near future Earth has been devastated by drought and famine, causing a scarcity in food and extreme changes in climate. When humanity is facing extinction, a mysterious rip in the space-time continuum is discovered, giving mankind the opportunity to widen their lifespan. A group of explorers must travel beyond our solar system in search of a planet that can sustain life.', '2020-09-27 11:37:56');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (6, 'Your Name', 'Mitsuha is the daughter of the mayor of a small mountain town. She''s a straightforward high school girl who lives with her sister and her grandmother and has no qualms about letting it be known that she''s uninterested in Shinto rituals or helping her father''s electoral campaign. Instead she dreams of leaving the boring town and trying her luck in Tokyo. Taki is a high school boy in Tokyo who works part-time in an Italian restaurant and aspires to become an architect or an artist.', '2020-09-27 11:37:56');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (7, 'Room', 'Jack is a young boy of 5 years old who has lived all his life in one room. He believes everything within it are the only real things in the world. But what will happen when his Ma suddenly tells him that there are other things outside of Room?', '2020-09-27 11:44:43');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (8, 'Castle in the Sky ', 'Laputa, a floating castle in the sky, was created by a mysterious race of people who long ago disappeared from the planet. A group of ruthless pirates suspect it has treasures and riches beyond imagination. ', '2020-11-02 10:59:31');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (9, 'Grave of the Fireflies ', 'A Japanese boy of 14 and his 4 year old sister, attempt to seek refuge from the atrocities of World War II in the small city of Kobe. In post-World War II Japan, a janitor finds a metal sweet container beside a deathly ill boy. ', '2020-11-03 10:59:31');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (10, 'My Neighbor Totoro ', 'Two sisters move to the country with their father in order to be closer to their hospitalized mother, and discover the surrounding trees are inhabited by Totoros, magical spirits of the forest. When the youngest runs away from home, the older sister seeks help from the spirits to find her. ', '2020-11-03 10:59:31');
INSERT INTO videoteca_db.film (id, title, description, created_at) VALUES (11, 'Toy Story ', 'What happens when you leave toys alone in a room? Well, it seems that they come to life! Young Andy''s playthings, including the sardonic Mr. Potatohead, a Slinky Dog with a southern drawl, an anxiety-ridden dinosaur, and some very gung-ho toy soldiers, are led by Woody, a pull-string cowboy doll whom Andy adores. But on his birthday, Andy receives a self-possessed, gadget-laden spaceman action figure named Buzz Lightyear, who quickly becomes Andy''s favorite.', '2020-11-04 09:27:32');